projects:
  client:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/client
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
